version: "3.8"
services:
  app:
    pull_policy: build
    build:
      context: ./
      target: prod
    environment:
      - NODE_ENV=production
    container_name: contact-app
    ports:
      - ${PORT:-3000}:3000
